### ISSUE TITLE
Missing Gda.ServerOperation static method

### ISSUE THREAD

**Issue by zeebok** [Valadoc/valadoc-org#173]
While trying to learn Gda I noticed that `Gda.ServerOperation.prepare_create_table` is missing.

**Comment by ZanderBrown** [comment]
The [method](https://gitlab.gnome.org/GNOME/libgda/blob/master/libgda/gda-server-operation.c#L322) is marked `Since: 6.0.0` & 6 hasn't been released yet so Valadoc documents 5

**Comment by zeebok** [comment]
The method I am talking about seems to be [this one](https://gitlab.gnome.org/GNOME/libgda/blob/master/libgda/gda-server-operation.c#L3104) which says `Since: 4.2.3`

**Comment by ZanderBrown** [comment]
As far as I'm aware that function isn't compatible with introspection

Introspection requires GError to be the last argument and in this declaration it isn't:
```
gda_server_operation_prepare_create_table_v (GdaConnection *cnc, const gchar *table_name, GError **error, ...)
```

So this function won't be introspected and therefore isn't in the vapi thus won't be in valadoc

Unfortunately GDA is riddled with these problems but v6 aims to improve this however it's still quite a way off.

As a general rule `*v` functions are only provided as a convenience and are simple wrappers to their none `v` counterparts because there are very hard to expose to other languages

**Comment by zeebok** [comment]
Ah alright that's really interesting, thanks for clarifying! I shall defer to you about what to do with this issue.

**Comment by ZanderBrown** [comment]
Well I understand your frustration but this isn't really a Valadoc issue so should probably be closed

**Comment by zeebok** [comment]
Sure thing, thanks again for the help.
